"""add composite index

Revision ID: 7ba359d6b342
Revises: 21a3e0a51f7e
Create Date: 2026-01-28 14:16:31.361404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba359d6b342'
down_revision: Union[str, None] = '21a3e0a51f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_content_slug_active', 'contents', ['slug', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_slug_active', table_name='contents')
    # ### end Alembic commands ###
